const students = [
  {
    id: 1,
    name: 'John Doe',
    year: 'Final',
    country: 'India',
    city: 'Delhi',
  },
  {
    id: 2,
    name: 'Jane Doe',
    year: 'First',
    country: 'India',
    city: 'Mumbai',
  },
  {
    id: 3,
    name: 'John Smith',
    year: 'Second',
    country: 'USA',
    city: 'New York',
  },
  {
    id: 4,
    name: 'Jane Smith',
    year: 'Third',
    country: 'USA',
    city: 'Chicago',
  },
  {
    id: 5,
    name: 'John Cena',
    year: 'Final',
    country: 'India',
    city: 'Delhi',
  },
  {
    id: 6,
    name: 'Jane Cena',
    year: 'First',
    country: 'India',
    city: 'Mumbai',
  },
  {
    id: 7,
    name: 'John Wick',
    year: 'Second',
    country: 'USA',
    city: 'New York',
  },
  {
    id: 8,
    name: 'Jane Wick',
    year: 'Third',
    country: 'USA',
    city: 'Chicago',
  },
  {
    id: 9,
    name: 'John Snow',
    year: 'Final',
    country: 'India',
    city: 'Delhi',
  },
  {
    id: 10,
    name: 'Jane Snow',
    year: 'First',
    country: 'India',
    city: 'Mumbai',
  },
  {
    id: 11,
    name: 'John Doe',
    year: 'Second',
    country: 'USA',
    city: 'New York',
  },
  {
    id: 12,
    name: 'Jane Doe',
    year: 'Third',
    country: 'USA',
    city: 'Chicago',
  },
  {
    id: 13,
    name: 'John Smith',
    year: 'Final',
    country: 'India',
    city: 'Delhi',
  },
  {
    id: 14,
    name: 'Jane Smith',
    year: 'First',
    country: 'India',
    city: 'Mumbai',
  },
  {
    id: 15,
    name: 'John Cena',
    year: 'Second',
    country: 'USA',
    city: 'New York',
  },
];

export default students;
